# Set a custom prefix
Prefix: '&7DeathNote &8» '

# Enable debug messages?
#  WARNING: WILL cause spam in console! this is
#   a development option, put here for ease of development.
Debug: false

# Should the book have limited uses?
#  Upon hitting the cap, the book will be consumed.
#  Set to 0 to disable
BookUses: 0

# Should a recipe be registered to make the book craftable? (requires restart)
CraftingRecipe: false

# Should afflictions be triggered instantly or with a 40 second delay (true to the anime)
Instant: true

# Should the plugin track kills with the Death Note in a local database?
TrackKills: true

UpdateCheck:
  # Should the plugin notify OPs/Players with the plugins admin perm
  #  when a new update is available when they join/reload the plugin?
  MessageOnJoin: true
  MessageOnReload: true

Afflictions:
  Random: true
  Explosion: true
  Lightning: true
  Fire: true
  Poison: true
  Void: true
  Creeper: true
  Falling: true
  Arrows: true
  Anvil: true
  Suffocation: true
  Drowning: true
  Cow: true
  Lava: true
  Pig: true
  ArchangelsFury: true
  Nair: true
  Fangs: true
  Bees: true
