# Set a custom prefix
Prefix: '&7DeathNote &8» '

# Enable debug messages?
#  WARNING: WILL cause spam in console! this is
#   a development option, put here for ease of development.
Debug: false

# Should the plugin track kills with the Death Note in a local database?
TrackKills: true

UpdateCheck:
  # Should the plugin notify OPs/Players with the plugins admin perm
  #  when a new update is available when they join/reload the plugin?
  MessageOnJoin: true
  MessageOnReload: true

Afflictions:
  Random: true
  Explosion: true
  Lightning: true
  Fire: true
  Poison: true
  Void: true
  Creeper: true
  Falling: true
  Arrows: true
  Anvil: true
  Suffocation: true
  Drowning: true
  Cow: true
  Lava: true
  Pig: true
  ArchangelsFury: true
  Nair: true
